# Generated by Django 2.0.6 on 2018-06-09 22:33

import backend.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, db_index=True, max_length=128)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, default='', max_length=128)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('size_bytes', models.IntegerField(db_index=True, default=0)),
                ('content', models.FileField(db_index=True, max_length=1024, unique=True, upload_to=backend.models._get_upload_path)),
                ('content_sha', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64)),
                ('start', models.DateTimeField(blank=True, db_index=True, help_text='For Time-Series Files', null=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, help_text='For Time-Series Files', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='DB Insertion Time')),
                ('modified', models.DateTimeField(auto_now=True, help_text='DB Modification Time')),
                ('columns', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('processor_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('related_files', models.ManyToManyField(blank=True, related_name='_storedfile_related_files_+', to='backend.StoredFile')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='storedfile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='backend.Tag'),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
