# Generated by Django 2.0.6 on 2018-06-11 16:11

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=64)),
                ('slug', models.SlugField(default='', max_length=64)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('editors', models.ManyToManyField(related_name='edits_albums', to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(related_name='albums', to='backend.StoredFile')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owns_albums', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='views_albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=64)),
                ('start', models.DateTimeField(blank=True, db_index=True, help_text='For Time-Series Events', null=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, help_text='For Time-Series Events', null=True)),
                ('files', models.ManyToManyField(related_name='events', to='backend.StoredFile')),
            ],
        ),
    ]
